intensivmed/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('kompendium.urls', namespace='kompendium')),
]

kompendium/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Home page Blog mit tags
    url(r'^tagspage/(?P<pk>\d+)/$', views.tagspage, name='tagspage'),
    # Topics
    url(r'^topics/$', views.topics, name='topics'),
    # Subtopics
    url(r'^topics/(?P<topic_id>\d+)/$', views.subtopics, name='topic'),
    # Entries
    url(r'^topics/(?P<topic_id>\d+)/(?P<subtopic_id>\d+)/$', views.entry, name='entry'),
    # Links
    url(r'^links/$', views.links, name='links'),
    # US Art
    url(r'^echo/$', views.us_selektion, name='us_selektion'),
    # US Bilderlist
    url(r'^echo/(?P<us_bilderliste_id>\d+)/$', views.us_bilderliste, name='us_bilderliste'),
    # Calculators
    url(r'^calcs/$', views.calcs, name='calcs'),
        # Hyponatriaemie
    url(r'^calcs/hyponatremia$', views.rechner, name='rechner'),
        # BGA
    url(r'^calcs/bga$', views.bga, name='bga'),
    # EDIC
    url(r'^edic/$', views.edic, name='edic'),
] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

kompendium/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Button
from crispy_forms.bootstrap import (FormActions)
from django.core.exceptions import ValidationError


from .models import Rechner, BGA

class RechnerForm(forms.ModelForm):
    
    class Meta:
        model = Rechner
        fields = ['natrium', 'kalium', 'alter', 'geschlecht', 'kg', 'serumOsmo', 'uosmo', 'unatrium', 'blutzucker', 'bun']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    #helper.form_show_labels = False # hides the labels
    helper.label_class = 'col-sm-2 col-sm-offset-3'
    helper.field_class = 'col-sm-3' 
    helper.labels_uppercase = False
    helper.layout = Layout(
        Field('natrium', css_class='input-sm', placeholder="S-Na+ mmol/l"),
        Field('kalium', css_class='input-sm', placeholder="S-K+ mmol/l"),
        Field('alter', css_class='input-sm', placeholder="Alter"),
        Field('geschlecht', css_class='input-sm', placeholder="Geschlecht"),
        Field('kg', css_class='input-sm', placeholder="Gewicht"),
        Field('serumOsmo', css_class='input-sm', placeholder="Serum Osmo"),
        Field('uosmo', css_class='input-sm', placeholder="Harn Osmo"),
        Field('unatrium', css_class='input-sm', placeholder="Harn Natrium"),
        Field('blutzucker', css_class='input-sm', placeholder="Blutzucker"),
        Field('bun', css_class='input-sm', placeholder="BUN"),
        FormActions(Submit('Senden', 'Senden', css_class='btn-primary'))
    )

    def clean_natrium(self):
        data = self.cleaned_data['natrium']
        if data > 160:
            raise ValidationError('Falsch!')
        return data

class BGAForm(forms.ModelForm):
    
    class Meta:
        model = BGA
        fields = ['ph', 'bicarbonate', 'pco_two', 'base_excess', 'sodium', 'potassium','chloride', 'albumin', 'phosphate', 'lactate', 'serumOsmo', 'uosmo', 'blutzucker', 'bun', 'sodium_urine', 'potassium_urine', 'chloride_urine', 'urine_ph']

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-sm-2 col-sm-offset-3'
    helper.field_class = 'col-sm-3'
    helper.form_show_labels = True
    helper.layout = Layout(    
        Field('ph', css_class='input-sm'),
        Field('pco_two', css_class='input-sm'),
        Field('bicarbonate', css_class='input-sm'),
        Field('base_excess', css_class='input-sm'),
        Field('sodium', css_class='input-sm'),
        Field('potassium', css_class='input-sm'),
        Field('chloride', css_class='input-sm'),
        Field('albumin', css_class='input-sm'),
        Field('phosphate', css_class='input-sm'),
        Field('lactate', css_class='input-sm'),
        Field('serumOsmo', css_class='input-sm'),
        Field('uosmo', css_class='input-sm'),
        Field('blutzucker', css_class='input-sm'),
        Field('bun', css_class='input-sm'),
        Field('sodium_urine', css_class='input-sm'),
        Field('potassium_urine', css_class='input-sm'),
        Field('chloride_urine', css_class='input-sm'),
        Field('urine_ph', css_class='input-sm'),
        FormActions(Submit('Senden', 'Senden', css_class='btn-primary')),
        )

    def clean_ph(self):
        data = self.cleaned_data['ph']
        if data > 7.8:
            raise ValidationError('impossible!')
        return data

kompendium/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Topic, Subtopic, Entry, Kategorie, Link, US_Selektion, US_Bilderliste, News, EDIC, Rechner, BGA, Tag
from .forms import RechnerForm, BGAForm

# Create your views here.

def index(request):

    """ the home page for intensivmed """
    #tags importieren
    tags = Tag.objects.get(id=1)
    #tag = tags.news_set.get(id=17)
    tag = tags.news_set.all()

    tagss = Tag.objects.all()

    news_list = News.objects.order_by('-news_date_added')
    #news_list = News.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(news_list, 3)

    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)

    context = {'news' : news, 'tag' : tag, 'tagss' : tagss}

    return render(request, 'kompendium/index.html', context)

def tagspage(request, pk):
        tag = get_object_or_404(Tag, pk=pk)
        blog = tag.news_set.all()
        return render (request, 'kompendium/tagspage.html', {'tag' : tag, 'blog' : blog})
        # if request.method=='GET':
        #     #post = Tag.objects.get(pk=pk)
        #     taggie = request.GET.get('t.name')
        #     if not taggie:
        #         return render(request, 'kompendium/topics.html')
        #     else:
        #         tag = Tag.objects.get(name=taggie)
        #         return render(request, 'kompendium/tagspage.html', {'tag' : tag})
        # else:
        #     return render(request, 'kompendium/subtopics.html')

def topics(request):
    """ Show all topics """
    topics = Topic.objects.order_by('date_added')
    #topics = Topic.objects.all()
    context = {'topics' : topics}
    return render(request, 'kompendium/topics.html', context)

def subtopics(request, topic_id):
    """ Show subtopics """
    topics = Topic.objects.get(id=topic_id)
    subtopics = topics.subtopic_set.all()
    context = {'topics' : topics, 'subtopics' : subtopics}
    return render(request, 'kompendium/subtopics.html', context)

def entry(request, topic_id, subtopic_id):
    """ Show entry """
    topics = Topic.objects.get(id=topic_id)
    subtopics = Subtopic.objects.get(id=subtopic_id)
    entry = subtopics.entry_set.order_by('-date_added')
    context = {'entry' : entry}
    return render(request, 'kompendium/entries.html', context)

def links(request):
    kategorien = Kategorie.objects.all()
    context = {'kategorien' : kategorien}
    return render(request, 'kompendium/links.html', context)

def us_selektion(request):
    """ Show US links """
    auswahl = US_Selektion.objects.all()
    context = {'auswahl' : auswahl}
    return render(request, 'kompendium/echo.html', context)

def us_bilderliste(request, us_bilderliste_id):
    """ Show pic list """
    bilder_selektion = US_Selektion.objects.get(id=us_bilderliste_id)
    bilder_liste = bilder_selektion.us_bilderliste_set.all()
    context = {'bilder_selektion' : bilder_selektion, 'bilder_liste' : bilder_liste}
    return render(request, 'kompendium/us_bilderliste.html', context)

def calcs(request):
    """ Show all calculators """
    calcs = "Hyponatremia"
    bga = "BGA"
    context = {'calcs' : calcs, 'bga' : bga}
    return render(request, 'kompendium/calcs.html', context)

def rechner(request):
    if request.method != 'POST':
        form = RechnerForm()
    else:
        form = RechnerForm(data=request.POST)
        if form.is_valid():
            natrium = form['natrium'].value()
            kalium = form['kalium'].value()
            blutzucker = form['blutzucker'].value()
            bun = form['bun'].value()
            serumOsmo = form['serumOsmo'].value()
            alter = form['alter'].value()
            geschlecht = form['geschlecht'].value()
            kg = form['kg'].value()
            uosmo = form['uosmo'].value()
            unatrium = form['unatrium'].value()
            
            # auskommentiert ist einfachere methode mit @staticmethod
            a = Rechner()
            osmo_result = a.calculatedOsmolality(natrium, kalium, blutzucker, bun)
            #osmo_result = Rechner.calculatedOsmolality(natrium, kalium, blutzucker, bun)
            osmo_gap = a.osmolalGap(serumOsmo, osmo_result)
            #osmo_gap = Rechner.osmolalGap(serumOsmo, osmo_result)
            tbw = a.totalBodyWater(alter, geschlecht, kg)

            if osmo_gap > 10:
                osmo_warning = "increased Osmo gap. MAEDIE: methanole, acetone, ethanol, diuretics, ispropanolol, ethylene glycol"
            else:
                osmo_warning = ""

            if int(uosmo) < 100:
                uosmo_warning = "Water excess. Consider primary polydipsia, low solute intake, beer potomania."
            else:
                uosmo_warning = ""

            if int(unatrium) < 30:
                unatrium_warning = "Low effective arterial blood volume. ECF expanded: heart failure, liver failure, nephrotic syndrome. ECF reduced: diarrhea, vomiting, third spacing, remote diuretics."
            else:
                unatrium_warning = ""

            context = {'unatrium_warning' : unatrium_warning, 'uosmo_warning' : uosmo_warning, 'osmo_warning' : osmo_warning, 'natrium' : natrium, 'serumOsmo' : serumOsmo, 'uosmo' : uosmo, 'unatrium' : unatrium, 'osmo_result' : osmo_result, 'osmo_gap' : osmo_gap, 'tbw' : tbw}
            return render(request, 'kompendium/results.html', context)

    context = {'form' : form}
    return render(request, 'kompendium/rechner.html', context)

def bga(request):
    if request.method != 'POST':
        form = BGAForm()
    else:
        form = BGAForm(data=request.POST)
        if form.is_valid():
            ph = form.cleaned_data['ph']
            pco_two = form.cleaned_data['pco_two']
            bicarbonate = form.cleaned_data['bicarbonate']
            base_excess = form.cleaned_data['base_excess']
            sodium = form.cleaned_data['sodium']
            chloride = form.cleaned_data['chloride']
            albumin = form.cleaned_data['albumin']
            phosphate = form.cleaned_data['phosphate']
            lactate = form.cleaned_data['lactate']
            serumOsmo = form['serumOsmo'].value()
            uosmo = form['uosmo'].value()
            blutzucker = form['blutzucker'].value()
            bun = form['bun'].value()
            sodium_urine = form['sodium_urine'].value()
            potassium_urine = form['potassium_urine'].value()
            chloride_urine = form['chloride_urine'].value()
            potassium = form['potassium'].value()
            urine_ph = form['urine_ph'].value()

            list_names = (ph, pco_two, bicarbonate, base_excess, lactate, serumOsmo, uosmo, blutzucker, bun, sodium, potassium, chloride, phosphate, albumin, urine_ph, sodium_urine, potassium_urine
                , chloride_urine)
            
            x = BGA()

            # check the primary acid base disorder
            ph_text = x.check_ph(ph, pco_two, bicarbonate, base_excess)

            # adequate response ?
            expected_results = x.expected_results(ph, pco_two, bicarbonate, base_excess)

            # check for complex acid base disorder
            secondary_abd = x.secondary_abd(ph, pco_two, bicarbonate, base_excess)

            # check for lactic acidosis
            lactic_acidosis = x.lactic_acidosis(lactate, sodium, bicarbonate, chloride)
            lactate_ag_effect = x.lactate_ag_effect(lactate, sodium, bicarbonate, chloride)

            # osmolal gap
            osmo_result = x.calculatedOsmolality(sodium, potassium, blutzucker, bun)
            osmo_gap = x.osmolalGap(serumOsmo, osmo_result, sodium, potassium, blutzucker, bun)
            ogap = x.ogap(serumOsmo, osmo_result, sodium, potassium, blutzucker, bun)

            # check urinary anion gap
            hyperchlor_acidosis = x.hyperchlor_acidosis(sodium_urine, potassium_urine, chloride_urine)
            hyperchlor_acidosis_uag = x.hyperchlor_acidosis_uag(sodium_urine, potassium_urine, chloride_urine)
            




            pco_two_result = x.pco_two_checker(pco_two)
            be_result = x.be_checker(base_excess)
            ph_result = x.ph_checker(ph)
            
            # STEWART APPROACH #
            
            be_na = x.be_subsets_na(sodium)
            be_cl = x.be_subsets_cl(chloride, sodium)
            be_alb = x.be_subsets_alb(albumin, ph)
            be_lact = x.be_subsets_lact(lactate)
            be_uma = x.be_subsets_uma(base_excess, be_na, be_cl, be_alb, be_lact)
            be_na_diagnosis = x.be_diagnosis_na(be_na)
            be_cl_diagnosis = x.be_diagnosis_cl(be_cl)
            be_alb_diagnosis = x.be_diagnosis_alb(be_alb)
            be_lact_diagnosis = x.be_diagnosis_lact(be_lact)
            be_uma_diagnosis = x.be_diagnosis_uma(be_uma)
            

            ### hyperchloremic acidosis ####
            hyperchlor_acidosis_patho = x.hyperchlor_acidosis_patho()
            
            rta = x.hyperchlor_acidosis_rta(sodium_urine, potassium_urine, chloride_urine, potassium, urine_ph)
            
            ### hypochloraemische azidose ###
            hypochlor_alkalosis_patho = x.hypochlor_alkalosis_patho()
            hypochlor_alkalosis_cl = x.hypochlor_alkalosis_cl(chloride_urine)

            #traditional approach
            anion_gap = x.anion_gap(sodium, bicarbonate, chloride)
            albumin_adjust = x.albumin_adjust(albumin, phosphate, sodium, bicarbonate, chloride)
            #check_ph = x.check_ph(ph, pco_two, bicarbonate, base_excess)
            anion_gap_check = x.anion_gap_check(albumin, phosphate, sodium, bicarbonate, chloride)
            compare_be_ag = x.compare_be_ag(base_excess, sodium, bicarbonate, chloride)
            

kompendium/templates/kompendium/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, inital-scale=1">
    <title>Intensivmed.at</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet" type="text/css" href="{% static 'kompendium/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Rubik">
  </head>
  
  <body>
     <div class="container">
      <nav class="navbar navbar-inverse navbar-static-top">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
          <a class ="navbar-brand" href="{% url 'kompendium:index' %}">Home</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'kompendium:topics' %}">Kompendium</a></li>
            <li><a href="{% url 'kompendium:links' %}">Links</a></li>
            <li><a href="{% url 'kompendium:us_selektion' %}">Ultraschall</a></li>
            <li><a href="{% url 'kompendium:calcs' %}">Rechner</a></li>
            <li><a href="{% url 'kompendium:edic' %}">EDIC</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </nav>
  
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div class="row center-block">
        {% block content %}{% endblock content %}
      </div>
    </div>
  </body>
</html>

kompendium/templates/kompendium/bga_calc.html
{% extends "kompendium/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<!-- <div class="col-sm-8"> -->
  <form action="{% url 'kompendium:bga' %}" method='post'>
    {% csrf_token %}
    <!-- <div class="center-block col-sm-1"></div> -->

      <div class="row">
        <!-- <div class="center-block col-sm-10"> -->
        

          <div class="form-group">
          
            {% crispy form %}
        
          </div>
      
        <!-- </div> -->
      <!-- </div> -->

    <!-- <div class="center-block col-sm-1"></div> -->
  </form>
</div>
{% endblock content %}

kompendium/templates/kompendium/bga_result_ma.html
{% extends 'kompendium/base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-xs-12">
		<a href="{% url 'kompendium:bga' %}">Zurück zum Rechner</a>
	</div>
</div>
<p></p>

<div class="row">
	<div class="well well-sm col-sm-7 col-xs-7">
		<h4>Summary</h4>
		<p>
			pH : {{ list_names.0 }}</br>
			pCO2 : {{ list_names.1 }}</br>
			HCO3 : {{ list_names.2 }}</br>
			BE: {{ list_names.3 }}</br>
			Lactate: {{ list_names.4 }}</br>
			Serum Osmo: {{ list_names.5 }}</br>
			Harn Osmo: {{ list_names.6 }}</br>
			Blutzucker: {{ list_names.7 }}</br>
			BUN: {{ list_names.8 }}</br>
			Na: {{ list_names.9 }}</br>
			K: {{ list_names.10 }}</br>
			Cl: {{ list_names.11 }}</br>
			PO4: {{ list_names.12 }}</br>
			Albumin: {{ list_names.13 }}</br>
			Urine pH: {{ list_names.14 }}</br>
			Urine Na: {{ list_names.15 }}</br>
			Urine K: {{ list_names.16 }}</br>
			Urine Cl: {{ list_names.17 }}</br>
		</p>
		<p>
			simple acid base disorder:</br> 
			<b>{{ ph_text }}</b>
		</p>
		<p>
			normal compensatory changes?</br>
			{{ expected_results }}
		</p>
		<p>
			secondary acid base disorder:</br>
			<b>{{ secondary_abd }}</b>
		</p>

	</div>
</div>


<div class="row">
	<div class="well well-sm col-sm-3">
		<h4>Stewart approach</h4>
			<p class="well well-sm">
				pCO2: {{ pco_two_result }}</br>
				BE: {{ be_result }}</br>
				pH: {{ ph_result }}</br>
			</p>
		<h5>BE subsets:</h5>
			<p>
			{% if be_na %}
				BEna: {{be_na | floatformat:"0" }}</br>
			{% endif %}
			
			{% if be_cl %}	
				BEcl: {{be_cl | floatformat:"0" }}</br>
			{% endif %}
			
			{% if be_alb %}	
				BEalb: {{be_alb | floatformat:"0" }}</br>
			{% endif %}
			
			{% if be_lact %}	
				BElact: {{be_lact | floatformat:"0" }}</br>
			{% endif %}
			
			{% if be_uma %}	
				BEuma: {{be_uma  | floatformat:"0" }}</br>
			{% endif %}
			</p>
		<h5>Pathology</h5>
			<p class="well well-sm">
			{% if be_na_diagnosis %}	
				{{ be_na_diagnosis }}</br>
			{% endif %}	
			{% if be_cl_diagnosis %}
				{{ be_cl_diagnosis }}</br>
			{% endif %}
			{% if be_alb_diagnosis %}
				{{ be_alb_diagnosis }}</br>
			{% endif %}
			{% if be_lact_diagnosis %}	
				{{ be_lact_diagnosis }}</br>
			{% endif %}	
			{% if be_uma_diagnosis %}
				{{ be_uma_diagnosis }}</br>
			{% endif %}
			</p>
		<p>
			{% if be_cl < -2 %}
				<h6>Hyperchloremic acidosis</h6>
				{{ hyperchlor_acidosis_patho | safe }}</br>
				Urinary anion gap: {{ hyperchlor_acidosis | safe | floatformat:"0" }}</br>
				{{ hyperchlor_acidosis_uag | safe }}</br>
				{{ rta }}<br>
			{% endif %}
			{% if be_cl > 2%}
				<h6>Hypochloremic alkalosis</h6>
				{{ hypochlor_alkalosis_patho | safe }}
				{{ hypochlor_alkalosis_cl | safe }}
			{% endif %}
		</p>
	</div>



	<div class="well col-sm-3 col-sm-offset-1">
		<h4>Traditional approach</h4>
		<h5>Differential diagnosis using the urine chloride concentration:</h5>
			{% if hypochlor_alkalosis_cl %}
				This is a <b>{{ hypochlor_alkalosis_cl | safe }}</b> metabolic alkalosis.</br>
					{% if hypochlor_alkalosis_cl == "chloride responsive" %}
						<span id="bga_comment_style">(U-Cl < 20 mmol/l)</span>
					{% endif %}
					{% if hypochlor_alkalosis_cl == "chloride unresponsive" %}
						<span id="bga_comment_style">(U-Cl > 20 mmol/l)</span>
					{% endif %}
			{% endif %}		
	</div>


{% if secondary_abd == "Metabolic acidosis" %}
	<div class="well col-sm-3 col-sm-offset-1">
		<h4>Traditional approach</h4></br>
			<h5 class="well well-sm" style="background-color: orangered;">Anion Gap</h5>
				<p>
					Anion gap: {{ anion_gap | floatformat:"0" }}</br>
					<span id="bga_comment_style">AG = Na - K - Cl - HCO3 (all mmol/l). normal value 8-12 mmol/l.</span>
				</p>
				<p>
					Anion gap albumin and phosphate adjusted: {{ albumin_adjust | floatformat:"0" }}</br>
					<span id="bga_comment_style">AG adjusted for albumin and phosphate = 0.2 * albumin (g/dl) + 1.5 * phosphate (mmol/l)</span>
				</p>
				<p class="well well-sm">
					{{ anion_gap_check | stringformat:"s" | safe }}
				</p>
				<p class="well well-sm">
					{{ compare_be_ag | safe}}
				</p>

			{% if lactic_acidosis %}
					<p class="well well-sm">
						{{ lactic_acidosis | safe}}
					</p>
			{% endif %}	
				
				<!-- <p class="well well-sm">
					{{ lactate_ag_effect | safe}}
				</p> -->
			<h5 class="well well-sm" style="background-color: orangered;">Osmolar Gap</h5>
			{% if osmo_result %}
				<p>
					calculated Osmolarity: {{ osmo_result | floatformat:"0" | safe }}</br>
					<span id="bga_comment_style">mOsmol/l</p></span>
					Osmolar Gap: {{ ogap | floatformat:"0" }}</br>
					<span id="bga_comment_style">measured osmolality - calculated osmolality</span>
				</p>
			{% endif %}
			{% if osmo_gap %}
				<p class="well well-sm">
					{{ osmo_gap | safe}}
				</p>
			{% endif %}
			
			{% if anion_gap < 12 %}
			<h5 class="well well-sm" style="background-color: orangered;">Urinary Anion gap</h5>
				<p>
					Urinary anion gap: {{ hyperchlor_acidosis | safe | floatformat:"0" }}<br>
					<p class="well well-sm">
						{{ hyperchlor_acidosis_uag | safe }}		
					</p>
				</p>
			{% endif %}
	</div>
{% endif %}
	<div class="well col-sm-3 col-sm-offset-1">
		<h4>Metabolic alkalosis</h4>
		<p>Pure respiratory acidosis: the pCO2 will be elevated, the arterial pH decreased.</p>
		<p>
			In metabolic acidosis the expected pCO2 can be calculated:</br>
			pCO2 = 1.5 x HCO3 + 8</br>
			pCO2 = 40 + SBE
		</p>
		<p>
			Respiratory compensation takes up to 5 days.</br>
			In acute respiratory acidosis, SBE will be within the normal range and bicarbonate can be calculated:</br>
			HCO3 = [(pCO2 -40) / 10] + 24
		</p>
		<p>
			With chronic respiratory acidosis the expected SBE and bicarbonate can be estimated with:</br>
			SBE = 0.4 x (pCO2 - 40)</br>
			HCO3 = [(pCO2 - 40) / 3] +24</br>
		</p>
		<p>
			<div class="alert alert-danger">
				You always need to know the history of the patient ! </br>
				e.g. pCO2 60 and SBE +5 could also mean acute respiratory acidosis with superimposed metabolic alkalosis.
			</div>
		</p>

	</div>
</div>


<!-- <div class="row">
	<p>
		<img src="{% static "kompendium/lactic_acidosis.jpg" %}" alt="Picture of Rango" />
	</p>
</div> -->


{% endblock content %}

kompendium/templates/kompendium/bga_result_ralk.html
bga_result_ralk.html

kompendium/templates/kompendium/calcs.html
{% extends "kompendium/base.html" %}
{% block content  %}
<div class="calcs">
	<div class="text-center">
         <a class="btn btn-primary" href="{% url 'kompendium:rechner' %}"  role="button">{{ calcs }}</a>
         <a class="btn btn-warning" href="{% url 'kompendium:bga' %}"  role="button">{{ bga }}</a>
    </div>
</div>
{% endblock content %}

kompendium/templates/kompendium/edic.html
{% extends 'kompendium/base.html' %}
{% load bootstrap3 %}
{% block content %}
<div id="inhalt">
  <div class="container">
    <div class="row center-block col-sm-6">
      <a class="btn btn-default" href="{% url 'kompendium:index' %}"  role="button">zurück zu index</a> 
      {% for text in text %}
        <p> {{ text }} </p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

kompendium/templates/kompendium/rechner.html
{% extends "kompendium/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <form action="{% url 'kompendium:rechner' %}" method='post'>
    {% csrf_token %}
    <!-- <div class="center-block col-sm-1"></div> -->

      <div class="row">
       <!--  <div class="center-block col-sm-10"> -->
          <div class="form-group">
            {% crispy form %}
          </div>
        <!-- </div> -->
      </div>
    
    <!-- <div class="center-block col-sm-1"></div> -->
  </form>

{% endblock content %}

kompendium/templates/kompendium/us_bilderliste.html
{% extends 'kompendium/base.html' %}

{% block content %}

<p>Bilderliste:</p>
<ul>
  {% for bild in bilder_liste %}
    <li>
       {{ bild }}
    </li>
  {% empty %}
    <li>Es gibt noch keinen Eintrag.</li>
  {% endfor %}
</ul>
{% endblock content %}